### ISSUE TITLE
Circular motion calculator

### ISSUE THREAD

**Issue by Amit366** [Amit366/FunwithPhysics#102]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Add circular motion calculator to classical mechanics section

**Comment by Gourab-18** [comment]
Hii @Amit366 I am ready to work upon this. Can I work on this?

**Comment by Amit366** [comment]
@Gourab-18 I guess u r working on input field issue??

**Comment by Shoray2002** [comment]
@Amit366 pr done
