### ISSUE TITLE
FAQ's link on footer

### ISSUE THREAD

**Issue by KarishmaVanwari** [Amit366/FunwithPhysics#103]
The FAQ's link on footer does not open the FAQ's modal on click. (as it does when FAQ's clicked on navbar)

**Comment by KarishmaVanwari** [comment]
Hey @Amit366 I would like to work on this issue for Hacktoberfest 2021, if its okay with you?

**Comment by Amit366** [comment]
@KarishmaVanwari heyy this issue has already been addressed and it has been solved but hasn't been updated yet. So u can working on other calculator issues.
