### ISSUE TITLE
Add force formula in Classical mechanics

### ISSUE THREAD

**Issue by Amit366** [Amit366/FunwithPhysics#13]
**Describe the solution you'd like**
Add force calculator in classical mechanics along with some content about force. 

(on clicking classical mechanics it should open a contents page where there would be different topic names. Then on clicking the topic name a page should open where there is some content with images and then below it the calculator.)

**Comment by Prashantvik** [comment]
Hi Amit, I'd like to work on this.

**Comment by Amit366** [comment]
@Prashantvik heyy u can add but do u know exactly what u need to do??

**Comment by techabhi08** [comment]
hello @Amit366 sir, can you please assign this to me?

**Comment by mayank-wadhwa-git** [comment]
Can you please further elaborate on what is to be done.
I would like to work on this.

**Comment by Amit366** [comment]
@mayank-wadhwa-git in the classical mechanics section add a heading as force. Now on clicking the heading force, a calculator will open up. In the calculator page there should be some content about force and also force calculator.

**Comment by Amit366** [comment]
@mayank-wadhwa-git do u want to work on this issue??

**Comment by mayank-wadhwa-git** [comment]
Yes sir, I would like to try it.

**Comment by Amit366** [comment]
ok

**Comment by Hiteshsukhwani29** [comment]
I would to like to work on this issue under DCP'21. Please assign this to me

**Comment by Amit366** [comment]
@Hiteshsukhwani29 go ahead

**Comment by Amit366** [comment]
@Hiteshsukhwani29 send the PR by 6 Aug.

**Comment by Hiteshsukhwani29** [comment]
sure

**Comment by Hiteshsukhwani29** [comment]
okay
