### ISSUE TITLE
new "wekipedia links"

### ISSUE THREAD

**Issue by Padmanabh82** [Amit366/FunwithPhysics#164]
Hi folks,
I have a idea for `Physics calculator`. the idea is, in description of concept i can add [wikipedia](https://www.wikipedia.org/) links. Please assign this issue to me

**Comment by Amit366** [comment]
@Padmanabh82 like u wanna add the wikipedia links for each calculator?? And what is react type checking?

**Comment by Padmanabh82** [comment]
> And what is react type checking?

@Amit366 sir i want to mean [react prop types](https://reactjs.org/docs/typechecking-with-proptypes.html) and project is big i thing i cannot do it but i have done wikipedia links

**Comment by Padmanabh82** [comment]
> @Padmanabh82 like u wanna add the wikipedia links for each calculator??

ya in physics calculator. i will make a pr now see in it
