### ISSUE TITLE
Footer Section

### ISSUE THREAD

**Issue by Swastik1710** [Amit366/FunwithPhysics#18]
**Is your feature request related to a problem? Please describe.**
A good website has an awesome footer section.

**Describe the solution you'd like**
I would like to add a responsive footer section to the website.

**Describe alternatives you've considered**

**Additional context**

**Comment by Swastik1710** [comment]
Please assign this issue to me so that I can start working on it.

**Comment by Amit366** [comment]
@Swastik1710 could u explain what changes u wanna make as there is already a footer??

**Comment by Swastik1710** [comment]
Yeah sure.
So as of now the footer section is not quite differentiable due to the color scheme used.
Moreover, the contact column doesn't have any details.
Neither does it contain any icons which provide an awesome look.
The hover effects on the links are quite ordinary.
Also the copyright section is too thick and the text in it is hardly visible.
Do let me know your views on this @Amit366

**Comment by Amit366** [comment]
There is no logo yet so according to the space it would take make the changes. I found it interesting. So I go ahead @Swastik1710 . But after finishing with the footer send the screen shot. If it looks better then current one then u can send the PR.

**Comment by Swastik1710** [comment]
Okay @Amit366 , I would send you a screenshot regarding this.
Glad you found it interesting.

**Comment by Amit366** [comment]
@Swastik1710 start working on this one but don't send the PR before 10th. As some other project admins are saying that from 10th the program starts.

**Comment by Swastik1710** [comment]
Yeah okay.
Will keep that in mind.

**Comment by dgulve** [comment]
Can one issue be solved by only one person?

**Comment by Amit366** [comment]
@dgulve yes. Since only one feature can be added.

**Comment by Swastik1710** [comment]
![FireShot Capture 052 - Fun With Physics - localhost](https://user-images.githubusercontent.com/71871571/124282140-1c21f000-db68-11eb-9761-947b42214394.png)

Here's the footer.
Do let me know your views on this @Amit366

**Comment by Amit366** [comment]
It's looks cool.

**Comment by Swastik1710** [comment]
Ohkay so I'll send a PR as soon as the program starts.
