### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by Amit366** [Amit366/FunwithPhysics#2]
Add the logo to the webpage

**Comment by techabhi08** [comment]
@Amit366 sir please assign this to me

**Comment by techabhi08** [comment]
@Amit366 Sorry sir but I am not able to run this project on my PC. It would be very helpful if I can get the theme of website or the Screenshot of the home page, so that I can make the logo accordingly.

**Comment by Amit366** [comment]
@techabhi08 if u r not able to run the project, then u need to download node modules and then run it.

**Comment by Amit366** [comment]
@techabhi08 r u working on it??

**Comment by techabhi08** [comment]
Yes sir will try to submit by this weekend. The problem was that I was unable to run your project and this problem is coming only with this project. I contributed to other places too the code was running perfectly. That's why I asked for the theme of website so that I can make logo in that theme.

**Comment by Amit366** [comment]
@techabhi08 others are able to run it on their local system.

**Comment by Amit366** [comment]
Have u installed node moduls?

**Comment by techabhi08** [comment]
yes sir. I even thought that might my system requires new dependencies version so I ran npm modules to update those dependencies accordingly.

**Comment by techabhi08** [comment]
Ok sir will try again give me time till this weekend

**Comment by techabhi08** [comment]
Sir I installed again and it is opening now. Some vulnerabilities were there so I deleted them and now its running. I just want to confirm now that this project is labelled under DevIncept right?

**Comment by Amit366** [comment]
@techabhi08 yes it is under DevIncept

**Comment by techabhi08** [comment]
Okay sir will submit the PR on this weekend

**Comment by Amit366** [comment]
@techabhi08 any update??

**Comment by aditya687** [comment]
Please assign me this issue I will design the logo @Amit366

**Comment by Amit366** [comment]
@aditya687 the logo is already designed but u need to add it to the website. If u want to work then tell me

**Comment by aditya687** [comment]
Yes sir

**Comment by aditya687** [comment]
Sir, I'm unable to open this project. What shall I do if it is showing error?

**Comment by Amit366** [comment]
@aditya687 u need to install the node modules

**Comment by aditya687** [comment]
Sir, I have already installed and done a react project and that time it
shown this type of error but, don't know why it is showing now maybe due to
vulnerabilities I think so.

**Comment by Amit366** [comment]
@aditya687 there are no vulnerabilities as just now someone has sent a PR. Maybe u need to install for this project in its path.

**Comment by aditya687** [comment]
Okk, I'm checking once again

**Comment by aditya687** [comment]
Sorry sir, I couldn't help due to certain problems in npm updates and you can unassign me. I will look for other issues if possible except this issue.
