### ISSUE TITLE
Add small description

### ISSUE THREAD

**Issue by Amit366** [Amit366/FunwithPhysics#20]
**Describe the solution you'd like**
Add a small description below the icon of each topic.

**Comment by Swastik1710** [comment]
Hey @Amit366, can you please assign this issue to me.
I would love to work on this.

**Comment by techabhi08** [comment]
Hello @Amit366 Sir, can you please assign me this issue?

**Comment by Amit366** [comment]
@Swastik1710 is already working on it

**Comment by techabhi08** [comment]
okay sir.

**Comment by Swastik1710** [comment]
Hey  @Amit366 , is this fine?

![Screenshot 2021-07-11 153414](https://user-images.githubusercontent.com/71871571/125190968-a26fbd80-e25d-11eb-9fbd-eced67a169a6.jpg)

**Comment by Amit366** [comment]
Yeah
