### ISSUE TITLE
Adding Code of Conduct file

### ISSUE THREAD

**Issue by aakankshabhende** [Amit366/FunwithPhysics#21]
Creating a Code of Conduct which everyone must abide by and mentioning the Scope of this Code of Conduct.

**Comment by Amit366** [comment]
@aakankshabhende https://docs.google.com/forms/d/e/1FAIpQLSechAFsQtArBOd7YR1OUJGlexwShD7uPW68YtUJpSCbaZh1gg/viewform

Fill this form for the 3 PRs merged and labelled as DevIncept.

**Comment by Amit366** [comment]
Are u in the slack channel?

**Comment by aakankshabhende** [comment]
Yes @Amit366 

> Are u in the slack channel?

**Comment by Amit366** [comment]
Ok @aakankshabhende fill the above form for the 3 merged PRs  that are labelled

**Comment by aakankshabhende** [comment]
individually for the 3 PRs right? @Amit366 sir

**Comment by Amit366** [comment]
@aakankshabhende yes.

**Comment by Amit366** [comment]
And also here after any PR merged u need to fill the form.
