### ISSUE TITLE
Create an Issue & Pull Request Template 

### ISSUE THREAD

**Issue by payaldutta** [Amit366/FunwithPhysics#22]
AIM
Create a custom Issue and Pull Request Template.

Features
Make an Issue Template. Any new Contributor must be able to specify if it is a new script or enhancement to an older one. It should also be specified which language he is coding it in.

Make a Pull Request Template. Any new Contributor must be able to specify if he has met all the requirements like Clean Code, proper README and Documentation, Screenshots (If any) attached and more.

**Comment by payaldutta** [comment]
@Amit366 Do assign me this issue under DCP'21.
Thank You.

**Comment by Amit366** [comment]
@payaldutta there already exist an Issue and Pr templates

**Comment by payaldutta** [comment]
Okay, Thanks for informing.
