### ISSUE TITLE
Updating the minor errors in Readme.md

### ISSUE THREAD

**Issue by manasb15** [Amit366/FunwithPhysics#23]
There are a few small documentation errors in the readme file, I would like to correct them. 

@Amit366 please assign me this issue if you think it is okay.

**Comment by Amit366** [comment]
@manasb15 may I know the changes u wanna do??

**Comment by manasb15** [comment]
@Amit366 Sorry for not specifying. In sentences like:
How it differs from other problem-solving projects?
 FunwithPysics is open source
 If you think that you can add a new feature or want to fix a bug. We invite you to contribute to FunwithPhysics and make this project better.
 Are you bored with the long calculations?
 Thanks to these wonderful peoples 
 
 There are minor grammar errors in these

**Comment by Amit366** [comment]
Ok go ahead

**Comment by Amit366** [comment]
Please specify the mistake and what r the errors?

**Comment by manasb15** [comment]
@Amit366 Should i specify the mistakes here or in a PR?

**Comment by Amit366** [comment]
Yeah because it's waste to contribute by just correcting some spelling mistakes or anything. If u want then please contribute to the project.

**Comment by manasb15** [comment]
@Amit366 Thanks. I will contribute to the project as well soon!

**Comment by manasb15** [comment]
@Amit366 Can you assign me this under DCP21 label please?

**Comment by Amit366** [comment]
Yes it's is assigned under DCP21. The labels with the merged PRs will be counted. So don't worry. 
@manasb15
