### ISSUE TITLE
Add friction formula

### ISSUE THREAD

**Issue by Amit366** [Amit366/FunwithPhysics#31]
**Is your feature request related to a problem? Please describe.**
Add friction formula

**Describe the solution you'd like**
In classical mechanics section add the topic friction and then in that add the formula along with some contents. 
(On clicking classical mechanics it should open a contents page where there would be different topic names. Then on clicking the topic name a page should open where there is some content with images and then below it the calculator.)

**Comment by RakeshCharpe** [comment]
I would to like to work on this issue under DCP'21. Please assign to me.

**Comment by Amit366** [comment]
@RakeshCharpe are u working on this issue??

**Comment by RakeshCharpe** [comment]
Due to exams it delay so you can unassign me.

**Comment by devesh-2002** [comment]
I am a contributor under DCP21. May I look after this issue?

**Comment by Amit366** [comment]
@devesh-2002 yes u can try out

**Comment by Amit366** [comment]
@devesh-2002 any update??

**Comment by devesh-2002** [comment]
I won't be able to complete this due to some reasons, you can unassign me.

**Comment by ashish-patwal** [comment]
If it's still open can i work on this issue ?

**Comment by Amit366** [comment]
@ashish-patwal no, this isn't opened. U can try out other calculators

**Comment by souravseal99** [comment]
Hi @Amit366 , just completed the task.  making a PR shortly.

**Comment by Amit366** [comment]
Yes send
