### ISSUE TITLE
Add gravitation formulas in classical mechanics

### ISSUE THREAD

**Issue by Amit366** [Amit366/FunwithPhysics#32]
**Is your feature request related to a problem? Please describe.**
Add gravitation formula

**Describe the solution you'd like**
Add a section in classical mechanics and in that add the formula and also some content.

**Comment by Hiteshsukhwani29** [comment]
I would to like to work on this issue under DCP'21. Please assign this to me

**Comment by jatinjain001** [comment]
can anyone please give me idea like ? what we have to do ?

**Comment by Amit366** [comment]
@jatinjain001 hitesh is already working on it. U can try the other issues.

**Comment by Amit366** [comment]
@Hiteshsukhwani29 any update?? If not then @jatinjain001 can try out.

**Comment by ashish-patwal** [comment]
is this issue up for grab @Amit366 ?

**Comment by Amit366** [comment]
@ashish-patwal yes u can work on it

**Comment by ashish-patwal** [comment]
Thanks , i will start working on it ; )

**Comment by Amit366** [comment]
@ashish-patwal first ho through the readme file and check the setup of the project

**Comment by ashish-patwal** [comment]
sure i willl

**Comment by Amit366** [comment]
And for any queries u can ping me on slack

**Comment by ashish-patwal** [comment]
thank you for your assistance !

**Comment by Amit366** [comment]
@ashish-patwal can u complete it by 6 Aug??

**Comment by ashish-patwal** [comment]
Yeah . I can do that .

**Comment by Amit366** [comment]
@ashish-patwal check out the other calculator and design it in the same way.

**Comment by ashish-patwal** [comment]
yeah i was actually in between modifying the overall calculator function , when i saw this pull actually fixed all that . Saved me some extra work . Thanks to him .
