### ISSUE TITLE
Correct Readme file

### ISSUE THREAD

**Issue by VATSAL-IIT** [Amit366/FunwithPhysics#387]
In line number 145 of the readme file the directory funwithphysics is wrongly written and might give error upon running.

**Comment by VATSAL-IIT** [comment]
I want to correct this.

**Comment by Amit366** [comment]
@VATSAL-IIT its already corrected by someone.

**Comment by Amit366** [comment]
u can work on something else

**Comment by VATSAL-IIT** [comment]
okay
