### ISSUE TITLE
There is no navigation in any of the physics field(Classical, Thermo dynamics,  etc..)

### ISSUE THREAD

**Issue by jatinjain001** [Amit366/FunwithPhysics#39]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
I want the navigation through the learn page to the chosen field

**Describe alternatives you've considered**
Working on one by one field

**Additional context**

**Comment by Amit366** [comment]
@jatinjain001 for each field there will be a content page and then a calculator page. For that there are issues already open. If u want to add any calculator u can check out the issues.

**Comment by Amit366** [comment]
So I am closing this issue
