### ISSUE TITLE
Modifications in FAQ page

### ISSUE THREAD

**Issue by kumarishalini6** [Amit366/FunwithPhysics#43]
**Describe the bug**
There is no FAQ page found but the link is given
@Amit366  i want to make FAQ page can i ??

**Comment by Amit366** [comment]
@kumarishalini6 go ahead.

**Comment by Amit366** [comment]
See make it a pop up if u can. But if u r comfortable with a separate page then fine. But  a pop up is recommended.

**Comment by kumarishalini6** [comment]
> See make it a pop up if u can. But if u r comfortable with a separate page then fine. But a pop up is recommended.

Ok I'll , before sending PR I'll send video

**Comment by Amit366** [comment]
@kumarishalini6 any update?

**Comment by kumarishalini6** [comment]
> @kumarishalini6 any update?

Actually today was my last external , I am working on it

**Comment by kumarishalini6** [comment]
Can you suggest me some questions I am getting confused what to add?

**Comment by kumarishalini6** [comment]
Is this ok or need some changes??

https://user-images.githubusercontent.com/69043944/126213382-03b09b6c-1c5c-48ed-9b0b-03bbedf5de41.mp4

**Comment by Amit366** [comment]
The pop up is fine but on clicking the FAQ on the navbar directly the pop up should appear.

**Comment by Amit366** [comment]
@kumarishalini6 and also make it a whitish grey as it will match with the dark background.

**Comment by kumarishalini6** [comment]
Ok and questions??

**Comment by Amit366** [comment]
@kumarishalini6 the first question can be what is this website for?? 
2) How to use this website?

**Comment by kumarishalini6** [comment]
> @kumarishalini6 the first question can be what is this website for??
> 2) How to use this website?

Ok

**Comment by Amit366** [comment]
Ans 1) This website is to make your physics easy. Just enter the values into the formula and you will get the answer with the procedure. 
2) Just click on the Learn button on the homepage. Then choose the branch of physics and click on it. Next on the contents page choose the topic and then enjoy with the calculator.

**Comment by Amit366** [comment]
Q3) How to contact us? 
A3) on the navbar click on contact us and then write your queries or follow us on our social media handles.

**Comment by Amit366** [comment]
@kumarishalini6 are u interested in making the calculators?? If yes then dm me on slack and choose the calculator u wanna do from the issues section.

**Comment by kumarishalini6** [comment]
is it ok now ??

https://user-images.githubusercontent.com/69043944/126255281-48a27ac4-64f8-417c-804b-685659364df8.mp4

**Comment by Amit366** [comment]
@kumarishalini6 why have u made the pop up smaller. The pop up u did earlier was nice but the only thing I asked u was to show the pop up on clicking the FAQ. Previously what u did was , on clicking the FAQ u r redirected to a new FAQ page and then the pop up. It should be directly pop up.

**Comment by Amit366** [comment]
https://amit366.github.io/portfolio/ 
U can checkout the pop up services section. On clicking view more on services section.

**Comment by kumarishalini6** [comment]
![Fun With Physics - Personal - Microsoft​ Edge 7_20_2021 09_51_25 AM](https://user-images.githubusercontent.com/69043944/126261525-3fdb883a-e889-415a-afde-3d0f23044c73.png)

**Comment by Amit366** [comment]
@kumarishalini6 just make the background transparent and also change the color of the questions to whitish grey

**Comment by kumarishalini6** [comment]
> @kumarishalini6 just make the background transparent and also change the color of the questions to whitish grey. And also one more thing when u r displaying the pop up don't push down the contents of the home page

It's looking odd with transparent background

**Comment by Amit366** [comment]
@kumarishalini6 but if there is a pop up then I think it's natural to have the background transparent. Because in any website u see it's the same. And if u change the color of pop up to whitish grey then transparent background will be nice. Once try it.

**Comment by kumarishalini6** [comment]
![Fun With Physics - Personal - Microsoft​ Edge 7_20_2021 11_14_24 AM](https://user-images.githubusercontent.com/69043944/126268070-21a836d4-9f0e-4d1f-b8ee-5f9d0e51d564.png)

![Fun With Physics - Personal - Microsoft​ Edge 7_20_2021 11_14_34 AM](https://user-images.githubusercontent.com/69043944/126268110-fd3730e2-23d1-4d87-884b-cdb650cd6c6b.png)

**Comment by Amit366** [comment]
@kumarishalini6 why have u changed the pop up background to transparent?? I said the homepage background to be transparent

**Comment by Amit366** [comment]
That's why I sent u the sample pop up link above

**Comment by Amit366** [comment]
Wait let me explain u everything. 
First of all in a pop up the contents of the homepage shouldn't be pushed down. Next the pop up should have a whitish grey background with the questions in black color. Next the home page should be transparent.

**Comment by kumarishalini6** [comment]
https://user-images.githubusercontent.com/69043944/126300119-5427e7d7-8b4c-41f3-bc37-cff89a287b50.mp4

**Comment by Amit366** [comment]
@kumarishalini6 this is fine but can u make the home background transparent when clicked on FAQ?

**Comment by Amit366** [comment]
And one more Bring the heading FAQ for you to the center. And change the color to white

**Comment by kumarishalini6** [comment]
> @kumarishalini6 this is fine but can u make the home background transparent when clicked on FAQ?

I have tried this but don't know why the code is not working

**Comment by kumarishalini6** [comment]
> And one more Bring the heading FAQ for you to the center. And change the color to white

Ok

**Comment by kumarishalini6** [comment]
> > And one more Bring the heading FAQ for you to the center. And change the color to white
> 
> Ok

Done
