### ISSUE TITLE
Add momentum calculator

### ISSUE THREAD

**Issue by Amit366** [Amit366/FunwithPhysics#45]
**Is your feature request related to a problem? Please describe.**
Add momentum calculator

**Describe the solution you'd like**

In classical mechanics section add the topic momentum and then in that add the formula along with some contents.
(On clicking classical mechanics it should open a contents page where there would be different topic names. Then on clicking the topic name a page should open where there is some content with images and then below it the calculator.)

**Comment by souravseal99** [comment]
Hi @Amit366 , I would like to work on it, can we discuss a bit more about this issue..

**Comment by Amit366** [comment]
@souravseal99 heyy u can dm me on slack. If u have any doubt.
