### ISSUE TITLE
Modification in FAQ page

### ISSUE THREAD

**Issue by Amit366** [Amit366/FunwithPhysics#49]
**Is your feature request related to a problem? Please describe.**
Modify the FAQ page

**Describe the solution you'd like**
On clicking the FAQ link on the navbar make the home page transparent so that the FAQ alert pops up. And also make the transition from question to answer smooth using CSS.

**Comment by souravseal99** [comment]
Hi @Amit366 👋🏼, I would like to work on this.

**Comment by Amit366** [comment]
@souravseal99 go ahead.

**Comment by Amit366** [comment]
Make it like a proper pop up.

**Comment by aditya687** [comment]
I want to make the faq section much better if you assign me

**Comment by Amit366** [comment]
@souravseal99 is working if by Tuesday he doesn't finish then I will assign it to u.

**Comment by Amit366** [comment]
Ok @aditya687

**Comment by aditya687** [comment]
Okk sir, let him do this.

**Comment by souravseal99** [comment]
Thanks @Amit366 , just made the PR, please let me know if it seems good to you.
