### ISSUE TITLE
Error Measurements

### ISSUE THREAD

**Issue by Amit366** [Amit366/FunwithPhysics#53]
**Is your feature request related to a problem? Please describe.**
Add Error measurements calculator

**Describe the solution you'd like**
Just follow the momentum calculator and similar to it add the contents of error measurements

**Comment by ashish-patwal** [comment]
Can i work on this issue @Amit366 ?

**Comment by Amit366** [comment]
@ashish-patwal yes u can but add as much formula as possible

**Comment by Amit366** [comment]
and also if possible add some content

**Comment by ashish-patwal** [comment]
Yes i will .

**Comment by Amit366** [comment]
@ashish-patwal r u working on it??

**Comment by ashish-patwal** [comment]
yes , i had some other work to do urgently . That's why the delay .
