### ISSUE TITLE
Add some badges to the top of README

### ISSUE THREAD

**Issue by Umesh-01** [Amit366/FunwithPhysics#55]
### **Is your feature request related to a problem? Please describe.**
Add some more badges to the top of readme.md file, since the badges will be colorful and more attractive at the top of README.md file than the text the users will like it and after linking the badges it will also help them to navigate to different sections/ webpages like PRs, issues, contributors, etc.

![image](https://user-images.githubusercontent.com/83420185/128008736-fe5803ff-0960-4609-a362-b7d52bde4a8d.png)

### **Describe the solution you'd like**
I will add some badges at the top and also will add links related to them so that the README.md file will look more interactive and awesome.

- [ ] Will add some more badges
- [ ] Will align them to center
- [ ] Will link them to related webpages/sections
- [ ] Will make them of single type

**Comment by Amit366** [comment]
@Umesh-01 what type of badges??

**Comment by Umesh-01** [comment]
like the badges you have @Amit366, below Einstein's image...

**Comment by Amit366** [comment]
@Umesh-01 but all the badges are present. What extrau want to add??

**Comment by Umesh-01** [comment]
Have a look on this @Amit366 

![image](https://user-images.githubusercontent.com/83420185/128009592-ba6cb6e1-ec5f-4ee9-ba5f-81d08ced6c2a.png)

**Comment by Amit366** [comment]
Ok then go ahead but don't change the existing badges.

**Comment by Umesh-01** [comment]
at present time after clicking on the badges they takes us to page like this-

![image](https://user-images.githubusercontent.com/83420185/128009821-88c7ed5c-056d-4c8c-bd35-08409b58edaf.png)

I will add links to them so that they can take us to the related web page/section

**Comment by Umesh-01** [comment]
> Ok then go ahead but don't change the existing badges.

Should I make them all of single type or not??

**Comment by Umesh-01** [comment]
and btw I am not a part of DCP @Amit366 😄 
I am just a contributor...
