### ISSUE TITLE
force.jpg source is not present 

### ISSUE THREAD

**Issue by ashish-patwal** [Amit366/FunwithPhysics#60]
**Describe the bug**
force.jpg required for force section in classical mechanics section is missing from images folder 

**To Reproduce**
1. yarn start 

**Expected behavior**
The site should have loaded with the image force.jpg

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Amit366** [comment]
@ashish-patwal it is present.

**Comment by Amit366** [comment]
@ashish-patwal it is already present

**Comment by ashish-patwal** [comment]
you literally did it right now  🤣 !

**Comment by Amit366** [comment]
@ashish-patwal how would I know people r so eager to contribute to my project that they are finding out bugs. 😅😅 
I am pleased with it and from now on after merging any issue or if I find any bug, I will not solve it.

**Comment by ashish-patwal** [comment]
No it's cool . I was just doing the daily pull from the upstream and then the code crashed . Then i saw that the jpg was missing and just created the issue 😄 .

**Comment by Amit366** [comment]
@ashish-patwal if u want u can add the logo to the navbar. The logo image is present in the repo , u just need to add it to the website

**Comment by ashish-patwal** [comment]
ok , let me make the changes then .

**Comment by Amit366** [comment]
There is already an issue opened .Check it out

**Comment by ashish-patwal** [comment]
ok , i will see to it .
