### ISSUE TITLE
Side navbar

### ISSUE THREAD

**Issue by Amit366** [Amit366/FunwithPhysics#7]
**Describe the solution you'd like**
Add sidenavbar to display the different calculators

**Additional context**
Add it in such a way that further more contents could be added.

**Comment by aakankshabhende** [comment]
Can I work on this issue? @Amit366

**Comment by Amit366** [comment]
Are u a participant of DevIncept Summer of Code??

**Comment by aakankshabhende** [comment]
Yes

**Comment by Amit366** [comment]
Okay then but first I think we need a home page and then a sidenavbar. So I think you have to wait till the home page is done @aakankshabhende

**Comment by aakankshabhende** [comment]
So can I work on the home page first? @Amit366

**Comment by Amit366** [comment]
If u want to work on home page u can

**Comment by aakankshabhende** [comment]
Okaay

**Comment by Amit366** [comment]
@aakankshabhende just comment on that issue so that I can assign you

**Comment by aakankshabhende** [comment]
Thanks @Amit366

**Comment by Amit366** [comment]
@aakankshabhende but send the PR only after the program officially begins

**Comment by aakankshabhende** [comment]
Okaay

**Comment by Amit366** [comment]
@aakankshabhende I guess u have done this in the first PR itself??

**Comment by aakankshabhende** [comment]
Yes only bottom to top scroll button is left @Amit366

**Comment by Amit366** [comment]
@aakankshabhende BUT in the points ur this issue will not be considered. Since u have done it in one PR itself

**Comment by Amit366** [comment]
I would suggest just increase the font size of the nav items and send a Pr. So that u could get points for that too
