### ISSUE TITLE
Bug in Link tag

### ISSUE THREAD

**Issue by Amit366** [Amit366/FunwithPhysics#72]
**Describe the bug**
The link tag doesn't redirect to the top of the next page.

**Comment by laisfrigerio** [comment]
@Amit366 what's page I can test this issue?

**Comment by Amit366** [comment]
@laisfrigerio did u solve that gravitational force one??

**Comment by Amit366** [comment]
@laisfrigerio since you r working on 3 issues so send the pull request and then u can work on others.

**Comment by laisfrigerio** [comment]
@Amit366 I solved gravitational force  issue (in the following branch https://github.com/laisfrigerio/FunwithPhysics/tree/bug/gravitation-page)

**Comment by Amit366** [comment]
@laisfrigerio can u send the ss of the page??

**Comment by laisfrigerio** [comment]
@Amit366 what's mean "ss"?

**Comment by Amit366** [comment]
@laisfrigerio screenshot 😅😅

**Comment by laisfrigerio** [comment]
Aaah thanks @Amit366  I'll send the screenshot into pull request ;)

**Comment by laisfrigerio** [comment]
@Amit366  Can you say how to test this error (from this issue) please?

**Comment by Amit366** [comment]
I have assigned u this issue. And u can find the bug when u click the red button of physics calculator on home page.
