### ISSUE TITLE
Error in loading the gravitational force page

### ISSUE THREAD

**Issue by Amit366** [Amit366/FunwithPhysics#73]
**Describe the bug**
On clicking the Gravitational force button the page is blank. All the codes are written properly but there is some error. Correct it.

**Comment by laisfrigerio** [comment]
@Amit366 maybe, I could help in this issue.

The error is the following verification:

```
  const page = WPE_list.filter(data => (data.topic) === (match.params.topic))
  const details = page[0]
```

When we get in into "gravitational force" the topic is "Gravitational Force"

But the WPE_list has a list with topic "Work" and "Power"

Is different  the topic's name ("Gravitational Force"). That's why "page" variable is empty array. "Details" variable will be undefined and return an error.

Please, could you explain the right flux for this page?

**Comment by Amit366** [comment]
@laisfrigerio the main expectation is that when clicking Gravitational force there should open a page with different topics and then on clicking the specific topic then the calculator must open. But the issue is the page with different topics is opening but further the calculator is not opening. You can check the problem in the website.

**Comment by laisfrigerio** [comment]
@Amit366 in the following page: https://myfunwithphysics.web.app/classicalmechanics has some "topics"

If I click  "Momentum" is will open the following page: https://myfunwithphysics.web.app/classicalmechanics/calc/Momentum
If I click "Torque" is will open https://myfunwithphysics.web.app/classicalmechanics/calc/Torque

This two links has a singulatiry: they open a description about each topic with a formula

----

But if I click into "Gravitation" into https://myfunwithphysics.web.app/classicalmechanics page, this will not open a page wtih gravitation description and formula.

This open https://myfunwithphysics.web.app/classicalmechanics/calc/Gravitation with "Gravitation Force" option. And I think you want now two options: Force and Work.

I see you added some topics and content in `topics_data.js` and `wpe_data.js`. But I think content of those file are incomplete.

Could you please help me with content of "Force" and "Work" and fill de JSON with the desire options

Please, correct me If I misundestood somethig.

**Comment by Amit366** [comment]
@laisfrigerio see like on clicking work power energy , it opens a page where there is option for work and power and then when clicking anyone of them the description along with calculator opens up. Similarly for gravitation, there is an options page. On clicking on gravitational force the page is blank. The task is to find the error why the page is blank.

**Comment by Amit366** [comment]
And also there are issues for adding more calculators. If you feel that you can create calculators similar to the existing once then you can take up those issues.

**Comment by Amit366** [comment]
topics and content in topics_data.js and wpe_data.js are incomplete as more calculators are to be added for which there are different issues in the issues section.

**Comment by laisfrigerio** [comment]
Hello @Amit366 thanks for your reply and example. I understood now the purpose.

Can you please check is the image content is as expected?

![screencapture-localhost-3000-classicalmechanics-calc-gravitation-Gravitational-Force-2021-09-30-06_31_28](https://user-images.githubusercontent.com/20709086/135427778-3209d053-90a1-4e39-8a40-f728c846053c.png)

I fix error loading page and add some information about Gravitational Force, like formula, details, picture.

If yes, you could please assign this issue to me :)

**Comment by Amit366** [comment]
@laisfrigerio it's perfect but there is already a file with contents right?? And I think in that there is calculator part.

**Comment by Amit366** [comment]
Did u modify that file??

**Comment by laisfrigerio** [comment]
Actually, not
But I will correct.
Thanks for the advice
