### ISSUE TITLE
Adding more features to home page. 

### ISSUE THREAD

**Issue by Amit366** [Amit366/FunwithPhysics#74]
**Is your feature request related to a problem? Please describe.**
Add some more features to home page. 

**Describe the solution you'd like**
Create two sections below the Learn heading. On side add buttons related to computer topics like Networking, DBMS and on the other side add topics of science like Maths, Physics and so on. 
UI design should be good.

**Comment by laisfrigerio** [comment]
Hello @Amit366 

I would like to take this issue. Could you please share the links from topics, I mean, when user click the button, where do you want to redirect user? Redirect to a medium blog, open a modal with some content, etc??

**Comment by Amit366** [comment]
@laisfrigerio see I haven't decided the UI for the buttons on the home page. So it is upto u to make a good UI ans organize the buttons. And more feature in the sense add a button which will redirect to a problem solving section. Like on clicking the button, it should redirect to a page where there will be many mcq physics questions and the questions should appear one by one.

**Comment by laisfrigerio** [comment]
@Amit366 Okay. But the links will be from your site? in this issue, I should create the "buttons" and the pages where will be the mcq physics questions??

**Comment by Amit366** [comment]
@laisfrigerio There will be pages for mcq questions, for which the structure of the questions page will be designed. And later the questions can be added. So you can add a button and then if u can design the questions page.

**Comment by laisfrigerio** [comment]
Yes @Amit366

**Comment by laisfrigerio** [comment]
From while, I have the following:

![funwithfisica-home-section-1](https://user-images.githubusercontent.com/20709086/135499037-f07a8763-dc9f-4d35-96b2-fab82bfb0deb.png)

Do you have more suggestions? What do you think about it??

**Comment by Amit366** [comment]
@laisfrigerio this is also good but change the background according to the home page. And then if we keep this in the home page then do u have any idea of how to redirect the user to calculators page and also the mcq page(which is to be made)???

**Comment by Amit366** [comment]
And remember to send PRs for each issue separately so that each will be counted as a contribution in Hacktober fest.

**Comment by laisfrigerio** [comment]
@Amit366 about background: I decided to added a different bg for this area. 

What color do you prefer: white ou dark blue?

How to redirect?
- Which button is a link/anchor tag. Than you put href attribute for each button

**Comment by laisfrigerio** [comment]
![screencapture-localhost-3000-2021-09-30-21_03_22](https://user-images.githubusercontent.com/20709086/135546270-6347755e-1bcc-460d-8276-ea02b2e57754.png)

This an example of full path screenshot.

**Comment by laisfrigerio** [comment]
I have the following purpose:

![screencapture-localhost-3000-2021-09-30-21_37_29](https://user-images.githubusercontent.com/20709086/135548593-f025ee79-6249-4313-a427-a39434e398ec.png)

![screencapture-localhost-3000-2021-09-30-21_37_55](https://user-images.githubusercontent.com/20709086/135548594-f1b4a0be-aaab-4f59-9cf3-39a61c27ebfc.png)

**Comment by laisfrigerio** [comment]
Font from icons (free svg icons):

https://www.svgrepo.com/svg/56231/computer
https://www.svgrepo.com/svg/63408/blackboard

If you have other suggestion, feel free to share :)

**Comment by Amit366** [comment]
@laisfrigerio white bg is better. 

And do one thing remove the physics calculator in red on the home page and then add then if possible add a small pop on clicking the buttons.

**Comment by Amit366** [comment]
If u can u do the pop up else I will open a new issue for that

**Comment by laisfrigerio** [comment]
@Amit366  When you say "popup" is like a tooltip: https://www.w3schools.com/howto/howto_css_tooltip.asp

What type of text should have in the popup/tooltip?

**Comment by Amit366** [comment]
@laisfrigerio what I meant was like on hovering over the button it should show two options calculator and questions. Then according to the option chosen by the user it should be redirected.

**Comment by laisfrigerio** [comment]
@Amit366 but why button for calculator? Isn't only links for specific topics?

This project Will make calculator from math formulas?

**Comment by Amit366** [comment]
See u have kept the buttons right in the above image which u sent?? @laisfrigerio

**Comment by Amit366** [comment]
![image](https://user-images.githubusercontent.com/60662775/135607882-3a1ebce3-0da3-46ab-8f51-3fa83c9b5452.png)
   

See this looks nice. But only make sections like science topic and computer totopics

**Comment by laisfrigerio** [comment]
@Amit366 Alright. I'l update here and show you a screenshot ;)

**Comment by laisfrigerio** [comment]
@Amit366  a new proposal:

![screencapture-localhost-3000-2021-10-01-09_05_39](https://user-images.githubusercontent.com/20709086/135617162-41c38899-3e18-4411-9c6c-b50948f14674.png)

**Comment by Amit366** [comment]
@laisfrigerio don't use  the computer and science tags on each instead of it under a heading add the topics.

**Comment by laisfrigerio** [comment]
@Amit366  I think the following one is better (without "topic" word):

![better](https://user-images.githubusercontent.com/20709086/135617449-7c39d84d-9c46-48e2-9178-34725453308f.png)

**Comment by laisfrigerio** [comment]
@Amit366 I'll try a proposal, but I think tag is better

**Comment by Amit366** [comment]
@laisfrigerio if u feel tag is better then do one thing make computer and science topics on separate lines.

**Comment by laisfrigerio** [comment]
Done:

![done](https://user-images.githubusercontent.com/20709086/135618094-8ec7da0f-4e8c-42a8-a9d4-50d84d837ca2.png)

**Comment by Amit366** [comment]
@laisfrigerio it's good but in future many more topics will be added. So I hope it can be done easily??

**Comment by laisfrigerio** [comment]
@Amit366 Yeah

The pattern:

```
<li class="science">
  <p>Maths</p>
  <small className="topic science-topic">Science</small>
  <img src={blackboardSvg} alt="Icon"/>
  <a href="/">+</a>
</li>
```

Is ul list. Each item of list is a topic

**Comment by laisfrigerio** [comment]
And is responsive to mobile pages

**Comment by Amit366** [comment]
@laisfrigerio using ul is a good idea as more
