### ISSUE TITLE
Contact us

### ISSUE THREAD

**Issue by Amit366** [Amit366/FunwithPhysics#75]
**Is your feature request related to a problem? Please describe.**

Link the contact us on the navbar to the footer.

**Comment by aakankshabhende** [comment]
Can I work on this issue @Amit366?

**Comment by Amit366** [comment]
@aakankshabhende I am sorry I haven't seen ur message but if u want then u can contribute and if u are participating in hactoberfest then u can contribute once the event starts.

**Comment by KarishmaVanwari** [comment]
Hey @Amit366 , can I work on this issue for Hacktoberfest 2021 ?

**Comment by ShivamDecodes** [comment]
Hi amit bhaiya! 
I Also Want to work on your project. please assign me...
I am called coding here in my class....

**Comment by Amit366** [comment]
@ShivamDecodes as u can see it is already assigned to @KarishmaVanwari . U can view other unassigned issues.

**Comment by KarishmaVanwari** [comment]
Hey @Amit366 , I have created the PR. Please do review it.

**Comment by Amit366** [comment]
@KarishmaVanwari by Sunday it will be reviewed. Don't worry

**Comment by KarishmaVanwari** [comment]
Okay, thank you.
