### ISSUE TITLE
Footer FAQ

### ISSUE THREAD

**Issue by Amit366** [Amit366/FunwithPhysics#76]
**Is your feature request related to a problem? Please describe.**

On clicking the FAQ on footer section the same pop up should appear as the FAQ on the navbar.

**Comment by nayabatir1** [comment]
Hi @Amit366 
I can help you with this task

**Comment by Amit366** [comment]
@nayabatir1 are u a hacktober fest participant??

**Comment by nayabatir1** [comment]
@Amit366 I'm new to open source don't know much about it.

**Comment by Amit366** [comment]
@nayabatir1 if you want to take part in hacktoberfest then u can and then contribute, but if you don't wanna take part and just contribute for learning then also u are welcome.

**Comment by nayabatir1** [comment]
@Amit366 I would really appreciate your help if you could guide me how to participate in hacktoberfest,

**Comment by Amit366** [comment]
@nayabatir1 I have pinned a message in the issues section. In that click on hacktoberfest. then u will be redirected to official website.

**Comment by nayabatir1** [comment]
@Amit366 sure will do by eod.
