### ISSUE TITLE
Warning: No duplicate props allowed

### ISSUE THREAD

**Issue by kunalkumar007** [Amit366/FunwithPhysics#78]
**Describe the bug**
I just cloned the repo in order to make some contribution and found that this repo is giving this warning as 
> No duplicate props allowed

**To Reproduce**
1. Go to 'src/Components/Classical Mechanics/Topics/Calculator.js'
2. Click on 'Terminal'
4. See error.

**Screenshots**
<img width="560" alt="Screenshot 2021-09-27 at 16 02 24" src="https://user-images.githubusercontent.com/55233386/134892517-37b90b7e-f884-479d-bb98-c213e3234324.png">

**Comment by Amit366** [comment]
@kunalkumar007 r u a participant of Hacktober fest??

**Comment by kunalkumar007** [comment]
Hy @Amit366 I am willing to participate in hacktoberfest. Hope this pull request helps.
