### ISSUE TITLE
Redesign footer

### ISSUE THREAD

**Issue by laisfrigerio** [Amit366/FunwithPhysics#81]
**Describe the solution you'd like**
I would like to purpose a redesigned to footer

**Describe alternatives you've considered**

**Additional context**
For example:
![funwithfisica-footer-redesign](https://user-images.githubusercontent.com/20709086/135430616-922f7fc5-bd60-4c14-bb7c-7e80ef3af73f.png)

- Using green color (from logo) instead of yellow;
- Added more spacing between elements;
- Changing box-shadow from social network buttons;
- Adding border around input elements;
- other? Please, suggest :)

**Comment by Amit366** [comment]
@laisfrigerio see the present footer is perfect as it was changed 3 to 4 times but if u want u can just change the color to green and add more spacing and nothing else.

**Comment by Amit366** [comment]
You can check out other issues and work on them else  if u wish u can add any other feature.

**Comment by laisfrigerio** [comment]
Change de color and spacing: 

![funwithfisica-footer-redesign-2](https://user-images.githubusercontent.com/20709086/135449386-4fc517e8-aa86-48e9-9ada-d6014eb7855b.png)

**Comment by Amit366** [comment]
@laisfrigerio yeah cool but don't send the PR now as there are already 3 pending PRs which will be cleared tomorrow, so u need to update ur cloned repo. After that u can send the PR.
