### ISSUE TITLE
Momentum calculator page is not responsive 

### ISSUE THREAD

**Issue by OmGole** [Amit366/FunwithPhysics#88]
**Describe the bug**
The mobile and tablet view for momentum calculator page is not responsive

**Comment by OmGole** [comment]
I know how to fix this issue. Can you assign this to me?

**Comment by Amit366** [comment]
@OmGole none of the calculators are responsive.

**Comment by OmGole** [comment]
I can make the page responsive if you assign me.

**Comment by Amit366** [comment]
@OmGole rectify the problems mentionedbin discord and then send the PR again
