### ISSUE TITLE
Formulas for SHM

### ISSUE THREAD

**Issue by Amit366** [Amit366/FunwithPhysics#91]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Add different formulas for SHM. Add formulas topic wise just like work power energy.

**Comment by souravseal99** [comment]
can I work on this?

**Comment by Amit366** [comment]
@souravseal99 make different for both waves and oscillation

**Comment by Amit366** [comment]
@souravseal99 make it just like kinematics calculator. Like the dropdown

**Comment by souravseal99** [comment]
> @souravseal99 make it just like kinematics calculator. Like the dropdown

for diff types of waves ( like sin, cos ) there would be an option in the dropdown, right?

**Comment by souravseal99** [comment]
and for oscillation, there could be two diff systems, like pendulum or spring-mass.

**Comment by souravseal99** [comment]
> @souravseal99 make it like different headings waves and oscillations(like work power) and then in that make the drop down like sine, cos and pendulum and spring mass accordingly

Ok, Clear.. 👍
