### ISSUE TITLE
Moment of Inertia

### ISSUE THREAD

**Issue by akashsahu006** [Amit366/FunwithPhysics#97]
**Is your feature request related to a problem? Please describe.**
There is no feature to calculate the moment of inertia of various different objects.

**Describe the solution you'd like**
There can be a feature to calculate the moment of inertia of different bodies like a ring, disc, solid cylinder, rectangular plate, rod, solid sphere etc.

**Comment by akashsahu006** [comment]
can I work on this issue to add this feature with several options of Ring, Disc, Hollow cylinder, triangular lamina, spherical shell, rod, solid sphere, ring, disc etc.

**Comment by Amit366** [comment]
@akashsahu006 u can.
join the discord channel for further doubts . link is in the readme

**Comment by Amit366** [comment]
@akashsahu006 add it just like work power energy section
