### ISSUE TITLE
Kinetic theory of gas Calculator

### ISSUE THREAD

**Issue by Amit366** [Amit366/FunwithPhysics#99]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Add this calculator in the thermodynamics section

**Comment by Shoray2002** [comment]
i will do this ,plz assign this me

**Comment by Amit366** [comment]
@Shoray2002 I will assign it to u. But resolve the conflict of ur PR

**Comment by Shoray2002** [comment]
thanks

**Comment by Amit366** [comment]
Ok

**Comment by Shoray2002** [comment]
Will be done, don't worry
